import assert from 'node:assert/strict';
const {Window} = await import(process.env.DOM_TEST_MODULE || 'happy-dom');
const window = new Window();
Object.assign(globalThis, {window, document: window.document, HTMLElement: window.HTMLElement,
  customElements: window.customElements, CustomEvent: window.CustomEvent});
customElements.define('ha-form',class extends HTMLElement {});
const {localDateTime, dueText, userTasks, isOverdue} = await import('../www/donetick-user-todo-card.js');
const calls=[]; let fail=false;
const hass={locale:{language:'en'},states:{'todo.all':{state:'2',attributes:{config_entry_id:'entry',circle_members:[{user_id:1,display_name:'Torben'}],tasks:[
  {task_id:1,assigned_to:1,name:'Weekly',description:'First line\n<script>plain text</script>',can_postpone:true,next_due_date:'2026-10-20T16:00:00Z'},
  {task_id:2,assigned_to:1,name:'One-off',can_postpone:false},
  {task_id:3,assigned_to:2,name:'Other user',can_postpone:true}
]}}},callService:async(...args)=>{calls.push(args);if(fail)throw new Error('Permission denied');}};
const card=document.createElement('donetick-user-todo-card');card.setConfig({entity:'todo.all',user_id:1});card.hass=hass;document.body.append(card);
const root=card.shadowRoot;
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const click=label=>root.querySelector(`[aria-label="${label}"]`).click();
const submit=()=>root.querySelector('form').dispatchEvent(new window.Event('submit',{cancelable:true}));
assert.equal(root.querySelectorAll('.row').length,2);
assert.equal(root.querySelectorAll('input[type=checkbox]').length,2);
assert.equal(root.querySelectorAll('.actions > button').length,5);
click('Reassign: Weekly');
assert.match(root.querySelector('.skip-prompt').textContent,/Add another user/);
assert.equal(root.querySelector('[aria-label="Save assignee"]').disabled,true);
click('Reassign: Weekly');assert.equal(root.querySelector('form'),null);
assert.equal(root.querySelector('.row').firstElementChild.className,'complete-checkbox');
assert.equal(root.querySelector('.row').lastElementChild.className,'actions');
assert.equal(root.querySelectorAll('.description-indicator').length,1);
assert.equal(root.querySelector('.description-indicator').getAttribute('icon'),'mdi:chevron-down');
assert.equal(root.querySelectorAll('.due .recurring').length,1);
assert.equal(root.querySelector('.recurring').getAttribute('icon'),'mdi:autorenew');
assert.equal(root.querySelector('.recurring').getAttribute('aria-label'),'Recurring task');
// Triggered recurrence has no skip action, but still needs a recurrence indicator.
hass.states['todo.all'].attributes.tasks[1].is_recurring=true;card.hass=hass;
assert.equal(root.querySelectorAll('.due .recurring').length,2);
hass.states['todo.all'].attributes.tasks[1].is_recurring=false;card.hass=hass;
assert.equal(root.querySelectorAll('.due .recurring').length,1);
const savedTasks=hass.states['todo.all'].attributes.tasks;
hass.states['todo.all'].attributes.tasks=[{task_id:4,assigned_to:1,name:'Past due',next_due_date:'2000-01-01T12:00:00Z'},{task_id:5,assigned_to:1,name:'Upcoming',next_due_date:'2100-01-01T12:00:00Z'},{task_id:6,assigned_to:1,name:'Undated'}];
card.hass=hass;
assert.equal(root.querySelectorAll('.due.overdue').length,1);
assert.equal(root.querySelector('.due.overdue').parentElement.querySelector('.name').textContent,'Past due');
hass.states['todo.all'].attributes.tasks=savedTasks;card.hass=hass;
const today=localDateTime(new Date()).slice(0,10);
hass.states['todo.all'].attributes.tasks=[{task_id:4,assigned_to:1,name:'Today only',next_due_date:today},{task_id:5,assigned_to:1,name:'Later',next_due_date:'2100-01-01T12:00:00Z'}];
card.setConfig({entity:'todo.all',user_id:1,display_filter:'today'});card.hass=hass;
assert.equal(root.querySelectorAll('.row').length,1);
assert.equal(root.querySelector('.name').textContent,'Today only');
assert.equal(card.getCardSize(),3);
card.setConfig({entity:'todo.all',user_id:1,display_filter:'overdue'});
assert.equal(root.querySelector('.empty').textContent,'No tasks for Torben · Filter: Overdue');
card.setConfig({entity:'todo.all',user_id:1,display_filter:'upcoming',upcoming_days:3});
assert.equal(root.querySelectorAll('.row').length,1);
assert.equal(root.querySelector('.name').textContent,'Today only');
hass.states['todo.all'].attributes.tasks=hass.states['todo.all'].attributes.tasks.filter(task=>task.task_id===5);card.hass=hass;
assert.equal(root.querySelector('.empty').textContent,'No tasks for Torben · Filter: Upcoming (3 days ahead)');
const editor=document.createElement('donetick-user-todo-editor');editor.setConfig({entity:'todo.all',user_id:1});editor.hass=hass;
const nativeForm=editor.shadowRoot.querySelector('ha-form');
assert.equal(nativeForm.data.display_filter,'all');
assert.equal(nativeForm.schema.find(field=>field.name==='display_filter').selector.select.options.length,4);
let changed;editor.addEventListener('config-changed',event=>{changed=event.detail.config;});
nativeForm.dispatchEvent(new CustomEvent('value-changed',{detail:{value:{...nativeForm.data,display_filter:'upcoming'}}}));
assert.equal(changed.display_filter,'upcoming');assert.equal(changed.user_id,1);
hass.states['todo.all'].attributes.tasks=savedTasks;card.setConfig({entity:'todo.all',user_id:1});card.hass=hass;
const noon=new Date('2026-10-24T12:00:00+02:00');
assert.equal(isOverdue('2026-10-24T09:00:00+02:00',noon),true);
assert.equal(isOverdue('2026-10-24T18:00:00+02:00',noon),false);
assert.equal(isOverdue('2026-10-24',noon),false);
assert.equal(isOverdue('2026-10-23',noon),true);
assert.equal(isOverdue(null,noon),false);
assert.equal(isOverdue('invalid',noon),false);
click('Skip occurrence: Weekly');assert.ok(root.querySelector('form'));assert.equal(calls.length,0);
click('Skip occurrence: Weekly');assert.equal(root.querySelector('form'),null);
click('Skip occurrence: Weekly');submit();await tick();
assert.deepEqual(calls.pop(),['donetick','postpone_task',{task_id:1,config_entry_id:'entry'}]);
assert.equal(root.querySelector('[role=status]'),null);
click('Change due date: Weekly');
assert.equal(root.querySelector('.save-action ha-icon').getAttribute('icon'),'mdi:content-save-outline');
assert.equal(root.querySelector('.save-action').disabled,true);
const callsBeforeUnchanged=calls.length;submit();await tick();assert.equal(calls.length,callsBeforeUnchanged);
assert.equal(root.querySelectorAll('[role=dialog], [popover]').length,0);
assert.equal(root.querySelectorAll('.action-panel button').length,2);
assert.equal(root.querySelector('.action-panel').previousElementSibling.className,'row');
assert.equal(root.querySelector('.action-panel ha-form').data.date,'2026-10-20');
assert.equal(root.querySelector('.action-panel ha-form').schema[0].schema.length,1);
click('Change due date: Weekly');assert.equal(root.querySelector('form'),null);
click('Change due date: Weekly');
const dateFields=()=>root.querySelector('.action-panel ha-form');
const callsBeforeInvalidDate=calls.length;
dateFields().dispatchEvent(new CustomEvent('value-changed',{detail:{value:{date:'',time:dateFields().data.time}}}));
submit();await tick();
assert.match(root.querySelector('.action-panel .error').textContent,/valid date and time/);
assert.equal(calls.length,callsBeforeInvalidDate);
dateFields().dispatchEvent(new CustomEvent('value-changed',{detail:{value:{date:'2026-10-24',time:dateFields().data.time}}}));
assert.equal(root.querySelector('.save-action').disabled,false);
card.hass=hass;assert.equal(dateFields().data.date,'2026-10-24');
click('Set time');assert.equal(dateFields().data.time,'18:00:00');
assert.ok(dateFields().schema[0].schema[1].selector.time);
click('Hide time');assert.equal(dateFields().schema[0].schema.length,1);
submit();await tick();
assert.deepEqual(calls.pop(),['donetick','update_task',{task_id:1,config_entry_id:'entry',due_date:'2026-10-24T16:00:00.000Z'}]);
assert.equal(root.querySelector('[role=status]'),null);
assert.equal(root.querySelector('form'),null);
assert.equal(localDateTime('2026-10-24T16:00:00Z'),'2026-10-24T18:00:00');
assert.equal(localDateTime('2026-10-27T16:00:00Z'),'2026-10-27T17:00:00');
assert.equal(dueText('2026-10-24T16:00:00Z','en',new Date('2026-10-26T12:00:00+01:00'),'24'),'Overdue · 2 days · 18:00');
assert.equal(dueText('2026-10-24T16:00:00Z','en',new Date('2026-10-24T12:00:00+02:00'),'24'),'Today · 18:00');
assert.equal(dueText('2026-10-25T16:00:00Z','en',new Date('2026-10-24T12:00:00+02:00'),'24'),'Tomorrow · 17:00');
assert.equal(dueText('2026-10-24','en',new Date('2026-10-24T12:00:00+02:00'),'24'),'Today');
assert.equal(dueText('2026-10-24T21:59:00Z','en',new Date('2026-10-24T12:00:00+02:00'),'24'),'Today');
assert.equal(dueText('2026-10-27T22:59:59Z','en',new Date('2026-10-26T12:00:00+01:00'),'24'),'Tomorrow');
assert.equal(dueText('2026-10-24T21:58:00Z','en',new Date('2026-10-24T12:00:00+02:00'),'24'),'Today · 23:58');
assert.equal(dueText(null,'en'),'No due date');
assert.equal(dueText('invalid','en'),'No due date');
assert.match(dueText('2026-10-24T16:00:00Z','en',new Date('2026-10-24T12:00:00+02:00'),'12'),/06:00 PM$/);
assert.deepEqual(userTasks({attributes:{tasks:[{task_id:1,assigned_to:1},{task_id:2,assigned_to:1,next_due_date:'2026-10-12T10:00:00Z'},{task_id:3,assigned_to:1,next_due_date:'2026-10-10T10:00:00Z'}]}},1).map(task=>task.task_id),[3,2,1]);
click('Change due date: Weekly');
dateFields().dispatchEvent(new CustomEvent('value-changed',{detail:{value:{date:'2026-10-26',time:dateFields().data.time}}}));
fail=true;submit();await tick();
assert.match(root.querySelector('.action-panel .error').textContent,/Permission denied/);
root.querySelector('form').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(root.querySelector('form'),null);
fail=false;click('Change due date: One-off');click('Skip occurrence: Weekly');
assert.equal(root.querySelectorAll('form').length,1);assert.equal(root.querySelector('form').getAttribute('aria-label'),'Skip occurrence: Weekly');
document.body.dispatchEvent(new window.PointerEvent('pointerdown',{bubbles:true}));assert.equal(root.querySelector('form'),null);
root.querySelector('[aria-label="Complete: Weekly"]').dispatchEvent(new window.Event('change'));await tick();
assert.deepEqual(calls.pop(),['donetick','complete_assigned_task',{task_id:1,config_entry_id:'entry'}]);assert.ok(root.querySelector('.completed input').checked);
await new Promise(resolve=>setTimeout(resolve,1050));
card.setConfig({entity:'todo.all',user_id:1,complete_control:'button',button_content:'icon_and_label'});
assert.equal(root.querySelectorAll('input[type=checkbox]').length,0);
// Multi-user labels depend on the view's scope, even when only one user's tasks match.
hass.states['todo.all'].attributes.circle_members.push({user_id:2,display_name:'Melissa'},{user_id:3,display_name:'Not eligible'});
hass.states['todo.all'].attributes.tasks[0].assignee_ids=[1,2];
card.setConfig({entity:'todo.all',user_id:'all'});
assert.equal(root.querySelectorAll('.row').length,3);
assert.equal(root.querySelectorAll('.assignee').length,3);
assert.match(root.querySelector('.assignee').textContent,/Torben/);
assert.ok(root.querySelector('[aria-label="Reassign: Weekly"]'));
click('Reassign: One-off');
assert.match(root.querySelector('.skip-prompt').textContent,/Add assignees to this task/);
assert.equal(root.querySelector('[aria-label="Save assignee"]').disabled,true);
click('Reassign: One-off');
click('Reassign: Weekly');assert.equal(root.querySelector('select').value,'1');
assert.equal(root.querySelector('.save-action').disabled,true);
assert.deepEqual([...root.querySelector('select').options].map(option=>option.value),['','1','2']);
click('Reassign: Weekly');assert.equal(root.querySelector('form'),null);
click('Reassign: Weekly');
let assignee=root.querySelector('select');assignee.value='2';assignee.dispatchEvent(new window.Event('change'));
assert.equal(root.querySelector('.save-action').disabled,false);
card.hass=hass;assert.equal(root.querySelector('select').value,'2');
fail=true;submit();await tick();
assert.match(root.querySelector('.action-panel .error').textContent,/Permission denied/);
assert.equal(root.querySelector('select').value,'2');calls.pop();
fail=false;submit();await tick();
assert.deepEqual(calls.pop(),['donetick','update_task',{task_id:1,config_entry_id:'entry',assigned_to:2}]);
assert.equal(root.querySelector('form'),null);
hass.states['todo.all'].attributes.tasks[0].assigned_to=2;card.hass=hass;
assert.match(root.querySelector('.assignee').textContent,/Melissa/);
card.setConfig({entity:'todo.all',user_id:1});assert.equal(root.querySelectorAll('.assignee').length,0);
assert.equal([...root.querySelectorAll('.name')].some(node=>node.textContent==='Weekly'),false);
card.setConfig({entity:'todo.all',user_id:'all',show_assignee:false,show_reassign:false});
assert.equal(root.querySelectorAll('.assignee').length,0);
assert.equal(root.querySelector('[aria-label="Reassign: Weekly"]'),null);
hass.states['todo.all'].attributes.donetick_user_id=1;
card.setConfig({entity:'todo.all',user_id:'all'});assert.equal(root.querySelectorAll('.assignee').length,0);
// Every action can be hidden independently, for either completion style.
for (const complete_control of ['checkbox','button']) {
  for (let mask=0;mask<16;mask++) {
    const visibility = Object.fromEntries(['show_complete','show_postpone','show_due_date','show_reassign'].map((key,index)=>[key,!!(mask & (1<<index))]));
    card.setConfig({entity:'todo.all',user_id:'all',complete_control,...visibility});
    for (const [key,label] of [['show_complete','Complete'],['show_postpone','Skip occurrence'],['show_due_date','Change due date'],['show_reassign','Reassign']]) {
      assert.equal(!!root.querySelector(`[aria-label="${label}: Weekly"]`),visibility[key],`${key} in ${complete_control} mode`);
    }
    if (!mask) { assert.equal(root.querySelectorAll('.actions,.complete-checkbox').length,0); }
  }
}
card.setConfig({entity:'todo.all',user_id:'all'});click('Change due date: Weekly');
assert.ok(root.querySelector('form'));
card.setConfig({entity:'todo.all',user_id:'all',show_due_date:false});assert.equal(root.querySelector('form'),null);
click('Show description: Weekly');
assert.equal(root.querySelector('.description-indicator').getAttribute('icon'),'mdi:chevron-up');
assert.equal(root.querySelector('.description').textContent,'First line\n<script>plain text</script>');
assert.equal(root.querySelector('.description script'),null);
assert.equal(root.querySelector('[aria-label="Show description: Weekly"]').getAttribute('aria-expanded'),'true');
click('Show description: Weekly');assert.equal(root.querySelector('.description'),null);
assert.equal(root.querySelector('.description-indicator').getAttribute('icon'),'mdi:chevron-down');
assert.equal(root.querySelector('[aria-label="Show description: One-off"]'),null);
const oneOffText=[...root.querySelectorAll('.task')].find(node=>node.querySelector('.name').textContent==='One-off');
assert.equal(oneOffText.tagName,'DIV');oneOffText.click();assert.equal(root.querySelector('.description'),null);
hass.states['todo.all'].attributes.tasks[1].description='  \n  ';card.hass=hass;
assert.equal(root.querySelector('[aria-label="Show description: One-off"]'),null);
click('Reassign: Weekly');assert.equal(root.querySelector('.description'),null);
click('Show description: Weekly');assert.equal(root.querySelector('form'),null);
root.querySelector('[aria-label="Show description: Weekly"]').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
assert.equal(root.querySelector('.description'),null);
card.setConfig({entity:'todo.all',user_id:'all'});click('Change due date: Weekly');
const picker=document.createElement('ha-dialog-date-picker');document.body.append(picker);
picker.dispatchEvent(new window.PointerEvent('pointerdown',{bubbles:true}));assert.ok(root.querySelector('form'));
picker.remove();document.body.dispatchEvent(new window.PointerEvent('pointerdown',{bubbles:true}));assert.equal(root.querySelector('form'),null);
hass.states['todo.all'].attributes.tasks[0].priority=4;
hass.states['todo.all'].attributes.tasks[1].priority=1;
hass.states['todo.all'].attributes.tasks[2].priority=3;
card.setConfig({entity:'todo.all',user_id:'all',sort_by:'priority'});
assert.deepEqual([...root.querySelectorAll('.name')].map(node=>node.textContent),['Weekly','Other user','One-off']);
card.setConfig({entity:'todo.all',user_id:'all',sort_by:'name'});
assert.deepEqual([...root.querySelectorAll('.name')].map(node=>node.textContent),['One-off','Other user','Weekly']);
assert.throws(()=>card.setConfig({entity:'todo.all',user_id:1,sort_by:'unknown'}),/valid sort order/);
console.log('Compact inline editing, repeated-tap toggles, preserved time, confirmed actions and feedback passed');
